[tool.black]
line-length = 80
skip-string-normalization = true
exclude = '''
/(
  \.eggs
  | .git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \.svn
  | _build
  | buck-out
  | build
  | dist
)/
'''
